// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RSO.Core.DiscussionModels;

public partial class DiscussionServicesRSOContext : DbContext
{
    public DiscussionServicesRSOContext()
    {
    }

    public DiscussionServicesRSOContext(DbContextOptions<DiscussionServicesRSOContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Discussion> Discussions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Discussion>(entity =>
        {
            entity.HasKey(e => e.DiscussionId).HasName("discussionid_pkey");

            entity.ToTable("Discussion");

            entity.Property(e => e.DiscussionId).UseIdentityAlwaysColumn();
            entity.Property(e => e.DiscussionText).IsRequired();
            entity.Property(e => e.PublishedOn).HasDefaultValueSql("CURRENT_TIMESTAMP");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}