// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RSO.Core.DiscussionModels;

public partial class Discussion
{
    public int DiscussionId { get; set; }

    public int UserId { get; set; }

    public int AddId { get; set; }

    public string DiscussionText { get; set; }

    public DateTime? PublishedOn { get; set; }
}